services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: bookshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

#  eureka-server:
#    build: ./eureka-server
#    ports:
#      - "8761:8761"
#
#  api-gateway:
#    build: ./api-gateway
#    ports:
#      - "8080:8080"
#    depends_on:
#      - eureka-server
#
#  book-service:
#    build: ./book-service
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgres
#      - eureka-server